"""
services/tts.py — Text-to-Speech via Microsoft Edge's professional neural voice synthesis.

Provides free, fast, high-quality voice synthesis for English, Russian, and Uzbek.
"""

from __future__ import annotations

import logging
import re
import edge_tts

logger = logging.getLogger(__name__)

# Uzbek Cyrillic → Latin transliteration table (official 1995 Uzbek Latin alphabet)
_UZ_CYR_TO_LAT: dict[str, str] = {
    'А': 'A',  'а': 'a',
    'Б': 'B',  'б': 'b',
    'В': 'V',  'в': 'v',
    'Г': 'G',  'г': 'g',
    'Ғ': "G'", 'ғ': "g'",
    'Д': 'D',  'д': 'd',
    'Е': 'Ye', 'е': 'ye',
    'Ё': 'Yo', 'ё': 'yo',
    'Ж': 'J',  'ж': 'j',
    'З': 'Z',  'з': 'z',
    'И': 'I',  'и': 'i',
    'Й': 'Y',  'й': 'y',
    'К': 'K',  'к': 'k',
    'Қ': 'Q',  'қ': 'q',
    'Л': 'L',  'л': 'l',
    'М': 'M',  'м': 'm',
    'Н': 'N',  'н': 'n',
    'О': 'O',  'о': 'o',
    'П': 'P',  'п': 'p',
    'Р': 'R',  'р': 'r',
    'С': 'S',  'с': 's',
    'Т': 'T',  'т': 't',
    'У': 'U',  'у': 'u',
    'Ф': 'F',  'ф': 'f',
    'Х': 'X',  'х': 'x',
    'Ц': 'Ts', 'ц': 'ts',
    'Ч': 'Ch', 'ч': 'ch',
    'Ш': 'Sh', 'ш': 'sh',
    'Щ': 'Sh', 'щ': 'sh',
    'Ъ': "'",  'ъ': "'",
    'Ы': 'I',  'ы': 'i',
    'Ь': '',   'ь': '',
    'Э': 'E',  'э': 'e',
    'Ю': 'Yu', 'ю': 'yu',
    'Я': 'Ya', 'я': 'ya',
    'Ў': "O'", 'ў': "o'",
    'Ҳ': 'H',  'ҳ': 'h',
    'Ҷ': 'J',  'ҷ': 'j',
}

_CYRILLIC_RE = re.compile(r'[А-яЁёҒғҚқҲҳЎўҶҷ]')

# Characters that break edge-tts SSML for Uzbek voice → safe replacements
_TTS_SAFE: dict[str, str] = {
    '«': '"', '»': '"',
    '‘': "'", '’': "'",  # curly single quotes
    '“': '"', '”': '"',  # curly double quotes
    '—': '-', '–': '-',  # em/en dash
    '…': '...',               # ellipsis
}


def _has_cyrillic(text: str) -> bool:
    return bool(_CYRILLIC_RE.search(text))


def _cyrillic_to_latin_uz(text: str) -> str:
    """Transliterate Uzbek Cyrillic text to Uzbek Latin for edge-tts compatibility."""
    return ''.join(_UZ_CYR_TO_LAT.get(ch, ch) for ch in text)


def _sanitize_for_uz_tts(text: str) -> str:
    """Replace characters that cause edge-tts to return no audio on the Uzbek voice."""
    return ''.join(_TTS_SAFE.get(ch, ch) for ch in text)

# Default voice mappings for backward compatibility with simple language codes
DEFAULT_VOICES = {
    "uz": "uz-UZ-MadinaNeural",
    "ru": "ru-RU-SvetlanaNeural",
    "en": "en-US-JennyNeural"
}

async def text_to_speech(text: str, voice_or_lang: str = "en") -> bytes:
    """
    Convert text to speech bytes (MP3) using edge-tts.
    Accepts full voice short names (e.g. 'uz-UZ-SardorNeural') or language codes ('uz', 'ru', 'en').
    """
    logger.info("Generating premium TTS for %d characters with voice/lang=%s…", len(text), voice_or_lang)
    
    # 1. Resolve voice selection
    voice = voice_or_lang
    normalized = voice_or_lang.lower().split("-")[0]
    
    if "-" not in voice_or_lang:
        # It's a language code, map it to our default voice
        voice = DEFAULT_VOICES.get(normalized, DEFAULT_VOICES["en"])
        
    logger.debug("Selected edge-tts voice: %s", voice)
    
    # 2. Transliterate Uzbek Cyrillic → Latin (edge-tts uz-UZ voices require Latin script)
    if voice.startswith("uz-"):
        if _has_cyrillic(text):
            logger.info("Transliterating Uzbek Cyrillic → Latin for TTS (%d chars)", len(text))
            text = _cyrillic_to_latin_uz(text)
        text = _sanitize_for_uz_tts(text)

    # 3. Synthesize using edge-tts
    try:
        communicate = edge_tts.Communicate(text, voice)
        audio_bytes = b""
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_bytes += chunk["data"]
                
        if not audio_bytes:
            raise ValueError("No audio content generated by edge-tts")
            
        return audio_bytes
        
    except Exception as e:
        logger.error("Failed to generate TTS via edge-tts: %s", e)
        raise RuntimeError(f"TTS generation failed: {e}") from e
