"""
services/tts.py — Text-to-Speech via Microsoft Edge's professional neural voice synthesis.

Provides free, fast, high-quality voice synthesis for English, Russian, and Uzbek.
"""

from __future__ import annotations

import logging
import edge_tts

logger = logging.getLogger(__name__)

# Default voice mappings for backward compatibility with simple language codes
DEFAULT_VOICES = {
    "uz": "uz-UZ-MadinaNeural",
    "ru": "ru-RU-SvetlanaNeural",
    "en": "en-US-JennyNeural"
}

async def text_to_speech(text: str, voice_or_lang: str = "en") -> bytes:
    """
    Convert text to speech bytes (MP3) using edge-tts.
    Accepts full voice short names (e.g. 'uz-UZ-SardorNeural') or language codes ('uz', 'ru', 'en').
    """
    logger.info("Generating premium TTS for %d characters with voice/lang=%s…", len(text), voice_or_lang)
    
    # 1. Resolve voice selection
    voice = voice_or_lang
    normalized = voice_or_lang.lower().split("-")[0]
    
    if "-" not in voice_or_lang:
        # It's a language code, map it to our default voice
        voice = DEFAULT_VOICES.get(normalized, DEFAULT_VOICES["en"])
        
    logger.debug("Selected edge-tts voice: %s", voice)
    
    # 2. Synthesize using edge-tts
    try:
        communicate = edge_tts.Communicate(text, voice)
        audio_bytes = b""
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_bytes += chunk["data"]
                
        if not audio_bytes:
            raise ValueError("No audio content generated by edge-tts")
            
        return audio_bytes
        
    except Exception as e:
        logger.error("Failed to generate TTS via edge-tts: %s", e)
        raise RuntimeError(f"TTS generation failed: {e}") from e
